"""Utilities for synchronising a Notion database with ChatGPT summaries."""

from __future__ import annotations

from typing import Any, Dict, Iterable, Optional

from .config import Settings


def _extract_page_content(page: Dict[str, Any]) -> str:
    """Return a human readable representation of a Notion page."""

    if "content" in page and isinstance(page["content"], str):
        return page["content"]

    properties = page.get("properties", {})
    for candidate in ("Name", "title", "Summary", "Description"):
        property_data = properties.get(candidate)
        if not property_data:
            continue
        for key in ("rich_text", "title", "plain_text"):
            values = property_data.get(key)
            if isinstance(values, list) and values:
                first = values[0]
                if isinstance(first, dict):
                    plain_text = first.get("plain_text")
                    if isinstance(plain_text, str):
                        return plain_text
                elif isinstance(first, str):
                    return first
            elif isinstance(values, str):
                return values
    return ""


def build_summary_prompt(pages: Iterable[Dict[str, Any]]) -> str:
    """Generate a basic prompt that can be sent to an LLM."""

    parts = []
    for page in pages:
        title = page.get("title") or page.get("id") or "Unknown page"
        content = _extract_page_content(page)
        parts.append(f"Page: {title}\n{content}\n")
    return "\n".join(parts)


def request_summary(llm_client: Any, prompt: str) -> str:
    """Return the summary as generated by an arbitrary LLM client."""

    if hasattr(llm_client, "summarize"):
        return llm_client.summarize(prompt)
    if hasattr(llm_client, "create"):
        response = llm_client.create(prompt=prompt)
        return response.get("summary", "")
    raise AttributeError("Unsupported LLM client interface")


def update_page_summary(
    notion_client: Any, page_id: str, summary_property: str, summary_text: str
) -> None:
    """Update the summary property on a Notion page."""

    notion_client.pages.update(
        page_id=page_id,
        properties={
            summary_property: {
                "rich_text": [
                    {
                        "text": {
                            "content": summary_text,
                        }
                    }
                ]
            }
        },
    )


def append_change_log(
    notion_client: Any,
    change_log_page_id: str,
    page: Dict[str, Any],
    summary_text: str,
) -> None:
    """Append an entry to the change log page."""

    message = f"Updated {page.get('title') or page.get('id')} summary: {summary_text}"
    notion_client.blocks.children.append(
        block_id=change_log_page_id,
        children=[
            {
                "paragraph": {
                    "rich_text": [
                        {
                            "text": {
                                "content": message,
                            }
                        }
                    ]
                }
            }
        ],
    )


def sync_database(
    notion_client: Any,
    llm_client: Any,
    settings: Settings,
) -> None:
    """Synchronise the Notion database with freshly generated summaries."""

    response = notion_client.databases.query(database_id=settings.NOTION_DATABASE_ID)
    pages: Iterable[Dict[str, Any]] = response.get("results", [])

    for page in pages:
        prompt = build_summary_prompt([page])
        summary = request_summary(llm_client, prompt)
        update_page_summary(
            notion_client,
            page_id=page["id"],
            summary_property=settings.NOTION_SUMMARY_PROPERTY_NAME,
            summary_text=summary,
        )

        change_log_page_id: Optional[str] = settings.NOTION_CHANGELOG_PAGE_ID
        if change_log_page_id:
            append_change_log(
                notion_client,
                change_log_page_id=change_log_page_id,
                page=page,
                summary_text=summary,
            )
